name: Create and publish Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag: 
        type: string
    secrets:
      registery_userame:
        required: true
      registery_password:
        required: true
        
jobs:
    build:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      
      - name: Setup BuildX
        uses: docker/setup-buildx-action@v2.0.0
        
      - name: Login to the Registry
        uses: docker/login-action@v2.0.0
        with:
            username: abc
            password: abc123
#           username: ${{secrets.registry_username}}
#           password: ${{secrets.registry_password}}
#       - name: Set the tag
#         run: |
#           if[ -z "{{inputs.tag}}" ]
#           then
#             echo "final_tag=latest" >> $GITHUB_ENV
#           else
#             echo "final_tag=${{inputs.tag}}" >> $GITHUB_ENV
          
      - name: Build and Push the Image
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          push: true
#           tags: abc/{{inputs.image_name}}:${{env.final_tag}}

  
